Feature/backend coding guidelines
nanogiants/nanogiants-docs pull request #18
Opened 2024-06-11 08:31 UTC by ehrdi

2024-07-01 10:00 UTC, dasheck0 requested changes

2024-07-01 10:14 UTC, ehrdi commented on docs/backend/basic-guidelines.md
> +- **Approaches:**
we dont. whatever fits the specific needs for the project. let's not constrict the developers too much here

2024-07-01 10:23 UTC, ehrdi commented on docs/backend/basic-guidelines.md
> +  - **Error Messages:** Provide clear and meaningful error messages.
I wouldn't make it mandatory, but I can add the reference to it anyway

2024-07-01 10:24 UTC, ehrdi commented on docs/backend/basic-guidelines.md
> +- **Principle:** Provide mechanisms to handle large sets of data.
Isn't that a bit too much for this document?

2024-07-01 10:26 UTC, ehrdi commented on docs/backend/basic-guidelines.md
> +3. **Error Codes**
I don't think we should rely on that

2024-07-01 10:27 UTC, ehrdi commented on docs/backend/basic-guidelines.md
> +   - **Principle:** Document the structure of the database, including tables, columns, relationships, and constraints.
or you can use dbeaver to generate the ERD

2024-07-01 10:28 UTC, ehrdi commented on docs/backend/basic-guidelines.md
> +  - Edge cases and error handling.
do you think that is really necessary?

2024-07-02 06:22 UTC, dasheck0 approved these changes

2024-07-02 06:24 UTC, merged